./migrar-algo2-2025.sh eg-agricultores-kotlin master
./migrar-algo2-2025.sh eg-agricultores-kotlin refactor
./migrar-algo2-2025.sh eg-generics-kotlin master
./migrar-algo2-2025.sh eg-lista-correo-kotlin master
./migrar-algo2-2025.sh eg-lista-correo-kotlin 01-observers-constructor
./migrar-algo2-2025.sh eg-lista-correo-kotlin 02-observers-setter
./migrar-algo2-2025.sh eg-lista-correo-kotlin 03-observers-singleton
./migrar-algo2-2025.sh eg-lista-correo-kotlin 04-observers-service-locator
./migrar-algo2-2025.sh eg-manejo-proyectos-kotlin master
./migrar-algo2-2025.sh eg-maquina-helado-kotlin master
./migrar-algo2-2025.sh eg-microprocesador-kotlin master
./migrar-algo2-2025.sh eg-microprocesador-kotlin creacionales
./migrar-algo2-2025.sh eg-monedero-kotlin master
./migrar-algo2-2025.sh eg-ruletas-kotlin master
./migrar-algo2-2025.sh eg-ruletas-kotlin stubbing-roulette
./migrar-algo2-2025.sh eg-ruletas-kotlin stubbing-roulette-mockk
./migrar-algo2-2025.sh eg-ruletas-kotlin mock-tests
./migrar-algo2-2025.sh eg-seguros-kotlin master
./migrar-algo2-2025.sh eg-seleccion-personal-kotlin master
./migrar-algo2-2025.sh eg-stock-refactor-kotlin master
./migrar-algo2-2025.sh eg-stock-refactor-kotlin-resuelto master
./migrar-algo2-2025.sh eg-tarjeta-credito-kotlin master
./migrar-algo2-2025.sh eg-tarjeta-credito-kotlin 01-builder
./migrar-algo2-2025.sh eg-tarjeta-credito-kotlin 02-strategy
./migrar-algo2-2025.sh eg-tarjeta-credito-kotlin 03-decorator
./migrar-algo2-2025.sh eg-tarjeta-credito-kotlin 04-delegated-classes
./migrar-algo2-2025.sh eg-turistas-kotlin master

# ./migrar-algo2-2025.sh eg-vehiculos-kotlin master ya migrado
